### ISSUE TITLE
How to make any field "Required or Disabled" ?

### ISSUE THREAD

**Issue by InsertCart** [devinsays/options-framework-plugin#205]
Hello everyone,

I have question about option framework. How to make any field may be it's a Input or Checkbox or anything. I want to use **Disabled or Required** using option framework.I'm wondering if there is any option for this. I know about wordpress requirements but that's what i need for my project.

$options[] = array(
        'name' => __('Checkbox', 'esell'),
        'desc' => __('Enable Manually This Option .', 'project'),
        'id' => 'target',
        'std' => '1',
        'type' => 'checkbox'
                **'required' => 'true/false',
        'disabled' => 'true/false'**

);

Thanks for such a nice plugin

**Comment by Solinx** [comment]
Hi InsertCart,

The options framework passes on extra values as fields attributes, so I would expect "required" => "required" to work for you. 

If not, you could try to work with the filters that are applied when the field values are sanitised (e.g. 'of_sanitize_checkbox' or 'of_sanitize_text').

    add_filter('of_sanitize_checkbox', 'my_filter_function', 10, 2);
    
    function my_filter_function($value, $option) {
        if ($option['id'] === 'target') {
            ...
        }
    }
