### ISSUE TITLE
Section Title

### ISSUE THREAD

**Issue by josh-rathke** [devinsays/options-framework-plugin#207]
Hey there,

I just started using the theme version of this and it's AWESOME!

Just one question: is there any plan to include a section title and paragraph description for groups of settings that are still within the same tab? I would have a couple different immediate applications for this.

**Comment by devinsays** [comment]
Hi Josh. Glad you like the framework. Did you try using the "info" option. You should be able to add any text using that, including HTML if you need to also have header elements.
