### ISSUE TITLE
Get current tab id

### ISSUE THREAD

**Issue by picavizu** [devinsays/options-framework-plugin#213]
I need get the current tab id to create a conditional ( if(){} ) to print specific css to hide the save button in some tabs. i´m loading in two tags, external pages using iframe and these pages have his own save button.

Thanks a lot!

**Comment by devinsays** [comment]
I would just use javascript for that. Get current tab ID:

```javascript
$('nav-tab-wrapper .nav-tab-active').attr('id');
```

You can see how the tab switching works here:
https://github.com/devinsays/options-framework-plugin/blob/master/js/options-custom.js#L26

Just enqueue in an addition script the fires additional actions to hide/show what you need when tabs are clicked.

**Comment by picavizu** [comment]
Thanks devinsays,
I tested and work perfect.
