### ISSUE TITLE
How can I attach settings to the plugin rather than a theme?

### ISSUE THREAD

**Issue by booruguru** [devinsays/options-framework-plugin#215]
Currently the Options Framework seems to be saving plugin settings based on the current theme. Switching themes requires the settings to be re-established.

By default, the options.php ( file assumes the settings are based on the currently activated theme slug, but I had modified the file to use a fixed slug ($optionsframework_settings['id']). So I'm not really sure what's causing the problem.

Any suggestions?

**Comment by dipskakadiya** [comment]
Any update on this? I have same question.
