### ISSUE TITLE
Allow adding raw HTML instead of input fields.

### ISSUE THREAD

**Issue by gillchristian** [devinsays/options-framework-plugin#218]
I was wondering if is possible to add different content/customization to the pages. Say a download button for a XSL file, or and icon to the field name.

It would be very nice if is possible to add something like this:

```php
	$options[] = array(
		'name' 			=> '<i class="fa fa-facebook"> </i> Facebook',
		'id' 			=> 'facebook',
		'type' 			=> 'text',
		'placeholder'	=> 'Add your Facebook account'
	);

        $options[] = array(
		'content' 			=> "/* html content here like a button */",
	);
```

**Comment by devinsays** [comment]
You can use the "info" option. It allows you to output raw HTML: https://github.com/devinsays/options-framework-plugin/blob/master/options-check/options.php#L178
