### ISSUE TITLE
Make options available to different user groups

### ISSUE THREAD

**Issue by ultrawebsites** [devinsays/options-framework-plugin#219]
Great framework, thanks very much.

An enhancement that I would find useful, would be the ability to have some (or all) options available to users other than just 'admin' users. I think often it be great if some or all of the options could be updated by non-admin users, such as editors - as they are usually the ones managing the content (and which is what I'm using the options framework for).

**Comment by devinsays** [comment]
Hi. Sorry for the delayed response here.

The Options Framework requires the "edit_theme_options" capability in order to display the options panel: https://github.com/devinsays/options-framework-plugin/blob/master/includes/class-options-framework-admin.php#L123

You can filter that capability through the theme if you'd like to give someone with less permissions the ability to alter that.

Another option would be to give specific users the "edit_theme_options" capability. There are a few plugins that let you give custom roles. This one is by a great plugin developer: https://wordpress.org/plugins/members/

**Comment by ultrawebsites** [comment]
Thanks @devinsays.

Could you please explain this statement of yours, whilst I've done a fair bit of WordPress development I'm not sure what it means: "You can filter that capability through the theme if you'd like to give someone with less permissions the ability to alter that."

I've used Justin's Members plugin for to effect before, but don't really want to use it just to give them access to the theme options. 

I guess though that I am using the plugin moreso as "website options" rather than "theme options" - for example, to put the contact phone number and email in (in case it changes) etc.

**Comment by devinsays** [comment]
I just looked through the code again and realized there's also capabilities check here: https://github.com/devinsays/options-framework-plugin/blob/e5a4832f89c5c2d6710808c4cf93cb9be9f9632b/options-framework.php#L32

So I would need to add an additional filter to the plugin in order for you to enable the capabilities for users without edit_theme_options capability.

If you know the specific user you'd like to have those permissions, it might be easiest to just add the capability for that user. Example:

```
$user = new WP_User( $user_id );
$user->add_cap( 'edit_theme_options' );
```

More here: https://codex.wordpress.org/Function_Reference/add_cap. That might be a little more lightweight than installing the Members plugins.

**Comment by ultrawebsites** [comment]
Great, thanks @devinsays 

I was wanting 'Editor' role users to be able to view/change the theme/website options also, but I'll use the add_cap function then where appropriate, for the moment.

**Comment by devinsays** [comment]
You can add that capability to everyone with the "Editor" role rather than specific users. That's also covered in that link: https://codex.wordpress.org/Function_Reference/add_cap
