### ISSUE TITLE
Moved Sites, Lost Settings

### ISSUE THREAD

**Issue by vanpop** [devinsays/options-framework-plugin#77]
Exported a multisite DB that has options framework plugin working on many sites. Imported the SQL, but only see default settings for each site on it's settings page. I found that the DB has the data after the import, and it looks correct, but once I visit a subsite's options framework settings page, the values are overwritten in the DB by the defaults.

If I comment out the "optionsframework_setdefaults();" line at around 152 in options-framework.php, the settings aren't overwritten in the DB after visiting the site settings page, but they aren't displayed on the settings page either.

**Comment by swaranan** [comment]
i have a problem ..When i deactivate the plugin the whole option panel got disappear...
